<font face="arial" size="+2"><center><b>CONTACT US</font><p>

<font face="arial">For all inquiries, in the first instance, please email us at</font><p>

<font face="arial"><a href="mailto:manager@worldspecializedsearchengines.com">manager@worldspecializedsearchengines.com</a></font><p>

<font face="arial">Our Head Office is situated in Brisbane the Capital of Beautiful Sunny Queensland in Australia.</font><p>

<font face="arial">We are not a huge Organization by any ways, yet, but we know we have been on the right track for the last decades, assisting people of all ages, and experience, with making the Internet easier and simpler for you all.</font><p>

<font face="arial">As you may have seen, we have The Top 20 individual specialized finance search engine directories, which cannot be copied, all ending in the most powerful dot com URLs.</font><p>
 
<font face="arial">If you would like to work with us, building the finance search engine directories and data bases in certain countries or worldwide, plus indirectly assisting all those who wish to know more information about a Finance Category, Subject or Topic easily and simply, please do not hesitate to email us anytime.</font><p>

<font face="arial" size="+1"><b>Please contact us at</font><p>

<font face="arial">"River Place"<br>
82 Boundary Street<br>
Brisbane Queensland 4000 Australia<br>
Telephones: +61 7 3832 5566 and leave a message if we are busy, or<br>
Email: <a href="manager@worldspecializedsearchengines.com">manager@worldspecializedsearchengines.com</a></font><p>

<font face="arial">PS> Watch out, in the near future, for our latest Finance Internet TV Shows, with the very latest about the Finance Industry in the World via 20 minute weekly 24/7 Internet Specialized Finance TV Shows about the Newest, Greatest &amp; Hottest Updates Internationally</font>.