<font class="pn" size="+2"><center><b>CONTACT US</b></font><p>

<font>For all inquiries, in the first instance, please email us at</font><p>

<font>

<SCRIPT LANGUAGE="JavaScript" type="text/javascript">
gen_mail_to_link('manager','worldspecializedsearchengines.com','Contact Request')
</SCRIPT>
<NOSCRIPT>
<em>Email address protected by JavaScript. Activate javascript to see the email.</em>
</NOSCRIPT>

</font><p>

<font>Our Head Office is situated in Brisbane the Capital of Beautiful Sunny Queensland in Australia.</font><p>

<font>We are not a huge Organization by any means yet, but we know we have been on the right track for the last decades, assisting people of all ages, and experience, with making the Internet easier and simpler for everyone.</font><p>

<font>As you may have seen, we have many individual specialized finance search engine directories, which cannot be copied, all ending in the most powerful dot com URLs.</font><p>
 
<font>If you would like to work with us, assisting to build any of the many search engine directories and data bases in particular countries, or worldwide, plus indirectly assisting all those who wish to know more information about a multitude of Topics and Businesses under various Countries, Categories and, Subjects, easily and simply, please do not hesitate to email us anytime.</font><p>

<font size="+1"><b>Please contact us at</font><p>

<font>"River Place"<br>
82 Boundary Street<br>
Brisbane Queensland 4000 Australia<br>
Telephones: +61 7 3832 5566 and leave a message if we are busy, or<br>
Email:

<SCRIPT LANGUAGE="JavaScript" type="text/javascript">
gen_mail_to_link('manager','worldspecializedsearchengines.com','Contact Request')
</SCRIPT>
<NOSCRIPT>
<em>Email address protected by JavaScript. Activate javascript to see the email.</em>
</NOSCRIPT>

</font><p>

<font>PS: Watch out, in the near future, for our latest Worldwide Internet TV Shows, with the very latest about Various Industries in the World via 20 minute weekly 24/7 Internet Specialized TV Shows about the Most Recent, Greatest and Hottest, Up-To-The-Minute News and Industry Updates Internationally</font>.